Date.tryParseJSON = require('./tryParseJSON')
Date.compareByDate = require('./compareByDate')
Date.equal = require('./equal')
Date.equalDates = require('./equalDates')
Date.UTCFromValues = require('./UTCFromValues')
Date.UTCFromDate = require('./UTCFromDate')

Date.prototype.addDays = require('./addDays')
Date.prototype.addMonths = require('./addMonths')
Date.prototype.addYears = require('./addYears')
Date.prototype.resetTime = require('./resetTime')
Date.prototype.resetUTCTime = require('./resetUTCTime')