Array.prototype.last = require('./last')
Array.prototype.includes = Array.prototype.includes || require('./includes')
Array.prototype.find = Array.prototype.find || require('./find')
Array.prototype.filter = Array.prototype.filter || require('./filter')
Array.prototype.addIfNotExists = require('./addIfNotExists')
Array.prototype.remove = require('./remove')
Array.concatNotNull = require('./concatNotNull')